# ================================================
# 🔧 Leapcell 배포 설정 파일
# ================================================
# 이 파일은 프로젝트 루트 폴더에 저장하세요!

[app]
# 프로젝트 기본 정보
name = "theblack-gif-generator"
description = "THE BLACK SHOP 디아블로4 애니메이션 GIF 생성기"

[build]
# Python 버전 설정 (Playwright 호환성)
runtime = "python:3.10"

# 🔧 빌드 명령어 (패키지 설치 + Playwright 브라우저 설치)
build_command = """
pip install -r requirements.txt && \
playwright install chromium && \
playwright install-deps chromium
"""

# 🚀 서버 시작 명령어 (gunicorn 사용)
start_command = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app"

[resources]
# 🧠 메모리 설정 (Playwright 브라우저 때문에 넉넉하게)
memory = "1024MB"

# ⚡ CPU 설정 
cpu = "1000m"  # 1 vCPU

# ⏱️ 타임아웃 설정 (GIF 생성 시간 고려)
timeout = "300s"  # 5분

[environment]
# 🌍 환경변수 설정 (Supabase 정보)
# 주의: 실제 값은 Leapcell 웹 대시보드에서 설정해야 합니다!
SUPABASE_URL = "https://ssnmitgehgzzcpmqwhzt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzbm1pdGdlaGd6emNwbXF3aHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjI1MDgsImV4cCI6MjA2ODkzODUwOH0.u3FrSDh5qYeccQmn0PkOs4nfqIhXLSFHhpWj2JXhTrA"

# 🎭 Playwright 설정
PLAYWRIGHT_BROWSERS_PATH = "/tmp/ms-playwright"

# 🐍 Python 설정
PYTHONUNBUFFERED = "1"

[scaling]
# 📊 자동 스케일링 설정
min_instances = 0  # 사용하지 않을 때는 0개 (비용 절약)
max_instances = 2  # 최대 2개 인스턴스 (Hobby Plan 제한 고려)

# 🔥 스케일링 조건
scale_up_threshold = "70%"    # CPU 70% 이상시 확장
scale_down_threshold = "30%"  # CPU 30% 이하시 축소

[health_check]
# ❤️ 서버 상태 체크
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3

[logs]
# 📝 로그 설정
level = "info"
retention = "7d"  # 7일간 보관

[static]
# 📁 정적 파일 설정 (index.html, theblack.html 등)
enabled = true
directory = "static"
cache_duration = "1h"
